[manager]
cwd = { fg = "cyan" }

hovered         = { fg = "black", bg = "lightblue" }
preview_hovered = { underline = true }

find_keyword  = { fg = "yellow", bold = true, italic = true, underline = true }
find_position = { fg = "magenta", bg = "reset", bold = true, italic = true }

marker_selected = { fg = "lightgreen",  bg = "lightgreen" }
marker_copied   = { fg = "lightyellow", bg = "lightyellow" }
marker_cut      = { fg = "lightred",    bg = "lightred" }

tab_active   = { fg = "black", bg = "lightblue" }
tab_inactive = { fg = "white", bg = "darkgray" }
tab_width    = 1

count_copied   = { fg = "black", bg = "lightyellow" }
count_cut      = { fg = "black", bg = "lightred" }
count_selected = { fg = "black", bg = "lightgreen" }

border_symbol = "│"
border_style  = { fg = "gray" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "darkgray", bg = "darkgray" }

mode_normal = { fg = "black", bg = "lightblue",  bold = true }
mode_select = { fg = "black", bg = "lightgreen", bold = true }
mode_unset  = { fg = "black", bg = "lightmagenta", bold = true }

progress_label  = { bold = true }
progress_normal = { fg = "blue",  bg = "black" }
progress_error  = { fg = "red", bg = "black" }

permissions_t = { fg = "lightgreen" }
permissions_r = { fg = "lightyellow" }
permissions_w = { fg = "lightred" }
permissions_x = { fg = "lightcyan" }
permissions_s = { fg = "darkgray" }

[input]
border   = { fg = "lightblue" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "lightblue" }
active   = { fg = "magenta" }
inactive = {}

[tasks]
border  = { fg = "lightblue" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "black" }
cand            = { fg = "lightcyan" }
rest            = { fg = "darkgray" }
desc            = { fg = "magenta" }
separator       = "  "
separator_style = { fg = "darkgray" }

[help]
on      = { fg = "magenta" }
run     = { fg = "blue" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "black", bg = "white" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "lightcyan" },
  # Videos
  { mime = "video/*", fg = "lightmagenta" },
  # Audio
  { mime = "audio/*", fg = "lightyellow" },
  # Docs
  { mime = "application/pdf", fg = "lightred" },
  # Archives
  { mime = "application/zip",     fg = "lightyellow" },
  { mime = "application/gzip",    fg = "lightyellow" },
  { mime = "application/x-tar",   fg = "lightyellow" },
  { mime = "application/x-bzip2", fg = "lightyellow" },
  { mime = "application/7z-compressed", fg = "lightyellow" },
  # Dirs
  { name = "*/", fg = "lightblue" },
  # Executables
  { name = "*", is = "exec", fg = "lightgreen" },
  # Fallback
  { name = "*", fg = "white" },
]
