"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "$character"
right_format = "$directory$git_branch$git_status$cmd_duration"

[directory]
style = "bold fg:#8aadf4"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"

[directory.substitutions]
"Documents" = "docs"
"Downloads" = "dl"
"Dev" = "dev"

[git_branch]
symbol = " "
style = "fg:#c6a0f6"
format = "[$symbol$branch ]($style)"

[git_status]
style = "fg:#ed8796"
format = "[$all_status$ahead_behind ]($style)"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
up_to_date = ""
untracked = "?${count}"
modified = "!${count}"
staged = "+${count}"
deleted = "✘${count}"

[nodejs]
symbol = " "
style = "fg:#a6da95"
format = "[$symbol$version ]($style)"

[python]
symbol = " "
style = "fg:#eed49f"
format = "[$symbol$version ]($style)"

[rust]
symbol = " "
style = "fg:#f5a97f"
format = "[$symbol$version ]($style)"

[golang]
symbol = " "
style = "fg:#8bd5ca"
format = "[$symbol$version ]($style)"

[pixi]
style = "fg:#eed49f"
format = "[ $version($environment) ]($style)"

[cmd_duration]
min_time = 2_000
style = "fg:#6e738d"
format = "[󱦟 $duration ]($style)"

[character]
success_symbol = "[❯](bold fg:#a6da95)"
error_symbol = "[❯](bold fg:#ed8796)"
vimcmd_symbol = "[❮](bold fg:#c6a0f6)"

[line_break]
disabled = true
